### ISSUE TITLE
MigraDocPrintDocument not present in the mirgradoc Beta 5 release 

### ISSUE THREAD

**Issue by adrianlfns** [empira/MigraDoc#10]
Hello, 

  I'm using Migradoc Rendering printing. I tried to upgrade from migradoc 1.32 to 1.50 (beta 5) and I had to abort the upgrade because the class MigraDocPrintDocument was removed from the project.

MigraDoc/MigraDoc/src/MigraDoc.Rendering/Rendering.Printing/MigraDocPrintDocument.cs

**Comment by ThomasHoevel** [comment]
It's not a bug, it's a feature.
The class from the old code can still be used..
See also:  
http://forum.pdfsharp.net/viewtopic.php?f=8&t=3202
