### ISSUE TITLE
Port to .NET Standard and stop supporting legacy plattforms

### ISSUE THREAD

**Issue by MovGP0** [empira/MigraDoc#19]
## Expected Behavior

The library should work with .NET Standard without dependency on WPF and WinForms. Controls for WPF and WinForms should be put in a dedicated library. Support for different plattforms is not needed when ported to .NET Standard, which greatly simplifies both, the code base and the maintanence work needed for it. 

## Actual Behavior

Codebase is crappy because of backward compatibility hacks, which greatly increases the likelyhood for bugs and wastes lots of valuable developer time. 

The library does not work in .NET Core CLI applications. 

## Steps to Reproduce the Behavior

Read the code, or try to render PDF in a .NET Core application.

**Comment by ThomasHoevel** [comment]
This works are planned for version 1.60 or version 2.00.
