### ISSUE TITLE
Classes from packages PDFsharp and MigraDoc aren't imported to the project

### ISSUE THREAD

**Issue by ErSoul** [empira/MigraDoc#23]
Can't import the classes used in [here](http://pdfsharp.net/wiki/MigraDocFirstSteps.ashx), but [these one](http://pdfsharp.net/wiki/PDFsharpFirstSteps.ashx) I can.

Visual Studio 2017 simply doesn't seem to find them.

I'm using ASP.NET Core 2.1 on windows 10.

Maybe you can point which specefic packages from nugget should I install?

**Comment by ThomasHoevel** [comment]
There are NuGet packages with just PDFsharp and there are NuGet packages with PDFsharp&MigraDoc. If you want to use MigraDoc classes, get a package that includes them.

https://www.nuget.org/profiles/PDFsharp-Team

**Comment by ErSoul** [comment]
I have installed [this package](https://www.nuget.org/packages/PDFsharp-MigraDoc/1.50.5147), but still can't even import the *Document* class that says on the documentation.

**Comment by ErSoul** [comment]
![image](https://user-images.githubusercontent.com/4327047/55735667-cb0a0c80-59ef-11e9-8b30-79e1b63498e0.png)
Thats the installed package, and this is what VS2017 tells me to import:
![image](https://user-images.githubusercontent.com/4327047/55735759-fbea4180-59ef-11e9-8dd3-dabfb17b244a.png)

**Comment by ThomasHoevel** [comment]
Maybe a `using` is still missing.
Have you tried compiling the Hello World sample:  
https://github.com/empira/MigraDoc-samples

**Comment by ErSoul** [comment]
Yes, I had to import it manually... Weird that VS2017 doesn't list it. Thanks for the help!
