### ISSUE TITLE
Set PageWidth/PageHeight when PageFormat changes

### ISSUE THREAD

**Issue by NXTwoThou** [empira/MigraDoc#26]
New PdfSharp/MigraDoc user.  Got tasked updating some insanely old code using iTextSharp before they went commercial.  Looking for ways to make it easier on the next person.

One of the first things that jumps out at me is when you set the PageFormat it doesn't set the PageWidth/PageHeight.  Looking through forums, people talk about cloning, setting the PageWidth/PageHeight to Unit.Empty first, and all sorts of other random things trying to get it to collect the sizes and none of them worked for me to set my DefaultPageSetup to be Letter.  As far as I can see, it only gets set during FlattenPageSetup

How about changing PageSetup.cs PageFormat property to use PageSetup.GetPageSize if PageWidth/PageHeight are empty?
```
public PageFormat PageFormat
        {
            get { return (PageFormat)_pageFormat.Value; }
            set { _pageFormat.Value = (int)value;
                if (!_pageFormat.IsNull 
                    && _pageWidth.IsNull && _pageHeight.IsNull
                    )
                    PageSetup.GetPageSize((PageFormat)_pageFormat.Value, out _pageWidth, out _pageHeight);
            }
        }
```

Currently, this is how I'm getting around this.  I was surprised I didn't see it in any of the forum topics.  I didn't know to do it until I started poking around the source.  It's here in case anyone comes across it.

```
document.DefaultPageSetup.PageFormat = PageFormat.Letter;
Unit tempWidth= document.DefaultPageSetup.PageWidth;
Unit tempHeight= document.DefaultPageSetup.PageHeight;
        PageSetup.GetPageSize(document.DefaultPageSetup.PageFormat, out tempWidth, out tempHeight);
        document.DefaultPageSetup.PageWidth = tempWidth;
        document.DefaultPageSetup.PageHeight = tempHeight;
```

**Comment by ThomasHoevel** [comment]
Ugly things can happen when you change the DefaultPageSetup. Instead create a clone of DefaultPageSetup in your code and change that as needed.
Or start with an empty PageSetup and set format and margins as needed.
Or use an empty PageSetup for your section and use DefaultPageSetup only to access the default values.

Setting `PageFormat` for an empty PageSetup has the desired effect. Changing `PageFormat` for a clone of DefaultPageSetup has not and requires setting `PageWidth` and `PageHeight` to `Unit.NullValue`..

Your suggested edit sets page size on the first invocation only, but not when called again. I don't like that idea.

**Comment by NXTwoThou** [comment]
I could see ugly things happening if you change your DefaultPageSetup after adding a section.  Are there ugly things that can happen before adding a section?  It seems logical to tell someone they could only change DefaultPageSetup before they add their first section.

Let's just ignore me talking about DefaultPageSize as I think I muddled the issue by even going there.

Here's an example as to how things were confusing to me:

```
myPDF = myPDFDoc.AddSection();
myPDF.PageSetup = myPDFDoc.DefaultPageSetup.Clone();
myPDF.PageSetup.PageFormat = PageFormat.Letter;

SizeF AreaSize = new SizeF(Math.Abs(myPDF.PageSetup.PageWidth-myPDF.PageSetup.RightMargin - myPDF.PageSetup.LeftMargin), Math.Abs(myPDF.PageSetup.PageHeight-myPDF.PageSetup.BottomMargin - myPDF.PageSetup.TopMargin));
```

This looked okay at first, but then realized the page wasn't the right size.  I did some searching and saw that you have to set

```
myPDF.PageSetup.PageWidth = MigraDoc.DocumentObjectModel.Unit.Empty;
myPDF.PageSetup.PageHeight = MigraDoc.DocumentObjectModel.Unit.Empty;
```

Before setting PageFormat.  I did that and got -really- screwed up AreaSize.  

The only time GetPageSize gets called is during FlattenPageSetup.  That is only called during VisitSection.  That's only called during RenderDocument.

What I was suggesting is when a use set PageFormat, if PageWidth/PageHeight were empty, it would populate them then so anyone trying to do any math based on page size would have it available immediately.  Right now, it wouldn't be available until it's time to save.

**Comment by TH-Soft** [comment]
The intended use:
```
myPDF = myPDFDoc.AddSection();
// myPDF.PageSetup = myPDFDoc.DefaultPageSetup.Clone();
myPDF.PageSetup.PageFormat = PageFormat.Letter;
```

The problem now: detecting the "areaSize": For values that are "null" in PageSetup you have to use the value from DefaultPageSetup.

The solution with "Clone()" works fine for people using A4 format - and areaSize can easily be determined. If the desired format is not A4 the Clone() call makes things more complicated.

DefaultPageSetup should be immutable and any attempt to change a value should throw an exception. Period. Maybe it will be immutable in the future. Better treat it like immutable and do not call any setters.

Maybe PageSetup should have methods like "EffectivePageWidth" that never return null, but return the effective value from DefaultPageSetup instead. The "Clone()" call is no longer needed and the code that calculates areaSize will look nice and tidy.
