### ISSUE TITLE
Warning when compiling with NET Core

### ISSUE THREAD

**Issue by wonea** [empira/MigraDoc#28]
## Actual Behavior

Lots of warnings on build. The NuGet package needs to explicitly state the frameworks it supports.

![image](https://user-images.githubusercontent.com/557192/66035566-495cec80-e503-11e9-8460-6da36810c150.png)
****

## Steps to Reproduce the Behavior
 Compile with NET Core 2.2 or 3.0

**Comment by ThomasHoevel** [comment]
The NuGet package states the framework it was developed for and tested with.

**Comment by wonea** [comment]
Looking at the actual NuGet package shows no framework dependencies set apart from NET Framework 2.

![image](https://user-images.githubusercontent.com/557192/66040200-c8a3ed80-e50e-11e9-8144-451452cea1d6.png)

It should look something like this (below is an example)

![image](https://user-images.githubusercontent.com/557192/66040319-10c31000-e50f-11e9-9792-fb8285c83d79.png)

**Comment by ThomasHoevel** [comment]
Should it? It compiles against .NET 3.5, so why should there be more than net20?

**Comment by wonea** [comment]
Because net20 is not netcoreapp3.0
https://docs.microsoft.com/en-us/dotnet/standard/frameworks

net20 is long unsupported by Microsoft and a potential security issue to those wanting to use it. At the very least bump the framework up to 3.5
https://en.wikipedia.org/wiki/.NET_Framework_version_history

**Comment by ThomasHoevel** [comment]
1. .NET 3.5 still uses the CLR 2.0. So CLR 2.0 should still be supported and safe. The WPF build compiles against .NET 3.5.

2. This is github where you can download the complete source and compile against any .NET version you like.

3. A version that compiles against .NET 6 will be released soon.

**Comment by ThomasHoevel** [comment]
The current version 6.0.0 uses .NET 6.
