### ISSUE TITLE
Upper cell border not set

### ISSUE THREAD

**Issue by emaborsa** [empira/MigraDoc#32]
Hello,
I noticed that if I set the upper border to a cell, it does not work. If I set all borders it does:

`cell.Borders.Color = Colors.Blue; --> works`
`cell.Borders.Top.Color = Colors.Blue; --> does not work`

Expected:
![expected](https://user-images.githubusercontent.com/9129912/100338449-e10b7d00-2fd8-11eb-9939-7b67d3c9a183.png)

Actual:
![actual](https://user-images.githubusercontent.com/9129912/100338543-01d3d280-2fd9-11eb-85e5-0665a158985b.png)

[Table.Cell.Borders.Top.Missing.zip](https://github.com/empira/MigraDoc/files/5602088/Table.Cell.Borders.Top.Missing.zip)

**Comment by ThomasHoevel** [comment]
The border is showing with version 6.0.0.
