### ISSUE TITLE
Render RTF with special characters

### ISSUE THREAD

**Issue by warriorfenixSM** [empira/MigraDoc#33]
Hi,

I try to make a PDF and RTF with a custom text. This text contains special characters (ñ,º,´,) and when renderer Pdf it is work, but when i renderer in RFT format the characters not display correctly.
Please i need help.
Thanks

`        Dim rtfRenderer As MigraDoc.RtfRendering.RtfDocumentRenderer = New MigraDoc.RtfRendering.RtfDocumentRenderer()
        Dim myRenderer As PdfDocumentRenderer = New PdfDocumentRenderer(True) With {
            .Document = myDoc
        }
        myRenderer.RenderDocument()
        myRenderer.PdfDocument.Save(Path.Combine(offerValues.webPath, String.Format("{0}{1}", offerValues.idProject, ".pdf")))
        rtfRenderer.Render(myDoc.Clone(), offerValues.idProject + ".rft", offerValues.webPath)`

**Comment by TH-Soft** [comment]
Incomplete repro steps.
