### ISSUE TITLE
RTF renderer does not support base64-encoded images

### ISSUE THREAD

**Issue by crypto-rsa** [empira/MigraDoc#34]
## Expected Behavior
Images in MigraDoc documents encoded using base64 are correctly rendered in RTF.

## Actual Behavior
Such images do not appear in the rendered RTF.

## Reason
MigraDoc `Image` shape supports working with images encoded with base64. These have the "filename" set to `base64:<encoded image bytes>`. The PDF renderer supports these, too, but the RTF renderer does not - it always treats the filename as "real" and thus the rendering fails.

**Comment by ThomasHoevel** [comment]
Limitation of the current implementation.

**Comment by davidmartin2422** [comment]
Thank you for fixing this.  It works in my project perfectly.

**Comment by ThomasHoevel** [comment]
This has been fixed.
Fix will be included with version 6.0.0-preview-3 coming soon (May or June 2023 or so).
