### ISSUE TITLE
"Can not resolve reference: `MigraDoc.DocumentObjectModel`" eventhough it should

### ISSUE THREAD

**Issue by EORG-Dev** [empira/MigraDoc#39]
# Resources

I'm using MigraDoc within a shared project for multiple Xamarin Forms Apps.
This is the relevant Code:

`using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;`

```
// Setup
Document document = new Document();
Section section = document.AddSection();
Table table = section.AddTable();
// design Table
table.AddColumn(Unit.FromPoint(13));
table.AddColumn(Unit.FromPoint(13.5));
table.AddColumn(Unit.FromPoint(5));
table.AddRow();
table.AddRow();
table.AddRow();
// Fill Cell
table.Rows[1].Cells[1].AddParagraph("Test");
table.Borders.Width = 0.5;
table.Borders.Color = Colors.Black;
PdfDocumentRenderer renderer = new PdfDocumentRenderer();
renderer.Document = document;
renderer.RenderDocument();
renderer.Save(FinalFilePath);
```

The Editor shows no conflicts or other errors.

# Reporting an Issue Here
## Expected Behavior
The Code compiles sucessfully.

## Actual Behavior
On compilation an error is thrown: `Can not resolve reference: MigraDoc.DocumentObjectModel, referenced by Projectname. Please add a NuGet package or assembly reference for MigraDoc.DocumentObjectModel, or remove the reference to Projectname.`

## Steps to Reproduce the Behavior
Hard to tell. For me it was just creating a project and coping this in + referencing the offical nuget.

## Tried so far:
- clean rebuild
- new clean project
- removed all potential conflicts (PdfSharp and other pdf utilities)

Edit: Formating

**Comment by ThomasHoevel** [comment]
The official NuGet packages compile with .NET 3.5 or .NET 2.0 respectively. Maybe that's the problem.
There will be new packages that compile against .NET 6 soon.
Maybe you have to download the source and compile against the version that Xamarin needs.

**Comment by ThomasHoevel** [comment]
The new packages for .NET 6 have been published today.
