### ISSUE TITLE
Static GlobalFontSettings should be moved to an instance property

### ISSUE THREAD

**Issue by IanLedzion** [empira/MigraDoc#41]
When configuring GlobalFontSettings.FontResolver, an exception is occasionally thrown:

System.InvalidOperationException: Must not change font resolver after is was once used.
   at PdfSharp.Fonts.GlobalFontSettings.set_FontResolver(IFontResolver value)

The code is being called from a Hangfire service, and implementing a Mutex does not help:

```
            if (!fontResolverSet)
            {
                lock (fontResolverMutex)
                {
                    if (!fontResolverSet)
                    {
                        GlobalFontSettings.FontResolver = new FontResolver();
                        fontResolverSet = true;
                    }
                }
            }
```

To move to a more standard DI-based implementation, it would be better that the renderer be instantiated with a font resolver property:

```
            var renderer = new PdfDocumentRenderer()
            {
                Document = document,
                FontResolver = new FontResolver(),
            };
            renderer.RenderDocument();

```

**Comment by ThomasHoevel** [comment]
For us it works with a mutex.

`PdfDocumentRenderer` is a MigraDoc class, but FontResolver is a PDFsharp feature. The proposed change is very complicated.

**Comment by IanLedzion** [comment]
Still, Microsoft is clear with guidance that for working in a DI based environment :

- Avoid stateful, static classes and members. Avoid creating global state by designing apps to use singleton services instead.

https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines

**Comment by ThomasHoevel** [comment]
Feel free to rewrite the current 6.0.0 version in a DI-friendly way and make a pull request.
It is not always simple to modernize 15+ years old software. PDFsharp was not designed as a DI service.
