### ISSUE TITLE
Infinite Loop in ‎TopDownFormatter::FormatOnAreas

### ISSUE THREAD

**Issue by mnadeem-mercedes-hpp** [empira/MigraDoc#45]
The loop in `‎TopDownFormatter::FormatOnAreas` has the tendency to become an infinite loop in some cases.

I have personally experienced two cases,

1. I had a blank space right after a picture.
2. I had three pictures together on separate lines.

This infinite loop caused our web farm to go down and cause lots of trouble.

I have to discontinue the use of this plugin, but I think this plugin is great apart from this deadly bug and it can be fixed.

A cancellation token can prove very helpful in functions like these.

**Comment by ThomasHoevel** [comment]
We no longer maintain version 1.5. With 1.5, you miss all the bug fixes from the last six years.

Does this also occur with version 6.1.1 or 6.2.0 Preview 1?
Is there code to replicate the issue?

**Comment by mnadeem-mercedes-hpp** [comment]
My apologies, the issue I am facing is on version 6.1.1.

As far as the code is concerned, I can provide you with the code, however the content of the PDF is very dynamic.

The content (i.e. string str) contains HTML text and image tags with base64 source. 

Everything works perfectly fine normally, however in some cases it goes into a deadly infinite loop.

I have the following method that adds text and images in a paragraph.

> private Paragraph RenderTextWithPictures(Paragraph paragraph, string str)
>         {
>             FormattedText text = paragraph.AddFormattedText();
>             Regex regex = new Regex(@"<img\b[^>]*\bsrc\s*=\s*['""]?([^'"" >]+)[^>]*>", RegexOptions.ECMAScript);
>             PageSetup.GetPageSize(PageFormat.A4, out Unit pageWidth, out Unit pageHeight);
>             Match m = regex.Match(str);
>             if (m.Success)
>             {
>                 text.AddText(cleanHtml(str.Substring(0, m.Index)));
>                 Image image = new Image("base64:" + ExtractB64SourceFromImageTag(m.Value));
>                 if (image != null)
>                 {
>                     image.LockAspectRatio = true;
>                     if (image.Width.Point > pageWidth.Point || image.Width.IsEmpty)
>                     {
>                         image.Width = new Unit(pageWidth.Centimeter - 2.0 - paragraph.Format.LeftIndent.Centimeter, UnitType.Centimeter);
>                     }
>                     text.Add(image);
>                 }
>                 Match prev = m;
>                 while (prev.NextMatch().Success)
>                 {
>                     text.AddText(cleanHtml(str.Substring(prev.Index + prev.Length)));
>                     prev = prev.NextMatch();
>                     image = new Image("base64:" + ExtractB64SourceFromImageTag(prev.Value));
>                     image.LockAspectRatio = true;
>                     if (image.Width.Point > pageWidth.Point || image.Width.IsEmpty)
>                     {
>                         image.Width = new Unit(pageWidth.Centimeter - 2.0 - paragraph.Format.LeftIndent.Centimeter, UnitType.Centimeter);
>                     }
>                     text.Add(image);
>                 }
>             }
>             else
>             {
>                 text.AddText(cleanHtml(str));
>             }
>             return paragraph;
>             string cleanHtml(string html) => Regex.Replace(html, @"<.*?>", string.Empty);
>         }





>         protected string ExtractB64SourceFromImageTag(string imageTag)
>         {
>             return Regex.Match(imageTag, "<img.+?src=[\"'](.+?)[\"'].*?>", RegexOptions.IgnoreCase).Groups[1].Value.Replace("data:image/png;base64,", string.Empty);
>         }

**Comment by ThomasHoevel** [comment]
Please use the current site and please use the IssueSubmissionTemplate for code.
Code snippets are usually not helpful.

https://docs.pdfsharp.net/General/Issue-Reporting.html
